version: '3.8'
services:
  training:
    build:
      context: ./components/training
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./components/training:/workspace
    environment:
      - JUPYTER_TOKEN=huAUCRkXiqW3JJW2QuyWjoJPCHY6lTWvkW5c5SbcXdx2hZEeFdQShrVOBK67QXP2
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
