version: '3.8'
services:
  training:
    build:
      context: ./training/
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    devices:
      - /dev:/dev
    volumes:
      - ./training:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
      - UDEV=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
