services:
  # Database
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=organaizer
      - POSTGRES_PASSWORD=organaizer
      - POSTGRES_DB=organaizer
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: none
    ports:
      - "5432:5432"
  # Database Browser
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@organaizer.com
      PGADMIN_DEFAULT_PASSWORD: admin
    logging:
      driver: none
    volumes:
      - ./.data/pgadmin/:/var/lib/pgadmin/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:80"